import { useI18n, type Lang } from './i18n';
const words = {
  expiredItem:['已过期','Expired','期限切れ'],
  account:['网站账号','Site account','サイトアカウント'], login:['登录','Sign in','ログイン'], register:['注册','Register','登録'], setup:['初始化管理员','Create administrator','管理者を作成'], reset:['重置密码','Reset password','パスワードを再設定'],
  username:['用户名','Username','ユーザー名'], password:['密码（12–128 个字符）','Password (12–128 characters)','パスワード（12〜128文字）'], currentPassword:['当前密码','Current password','現在のパスワード'], invite:['邀请码','Invitation code','招待コード'], setupToken:['初始化口令','Setup token','初期設定トークン'], resetToken:['重置凭据','Reset token','再設定トークン'],
  usernameHint:['3–32 位小写字母、数字或下划线','3–32 lowercase letters, digits or underscores','半角小文字・数字・下線で3〜32文字'], submit:['继续','Continue','続ける'], working:['处理中…','Working…','処理中…'], logout:['退出网站账号','Sign out of Lumen','Lumenからログアウト'], changePassword:['修改密码','Change password','パスワード変更'], done:['已完成','Done','完了'],
  admin:['管理面板','Administration','管理画面'], back:['返回播放器','Back to player','プレーヤーへ'], source:['音源账号','Music source','音源アカウント'], users:['用户与邀请码','Users & invitations','ユーザーと招待'], service:['服务状态','Service status','サービス状態'],
  sourceHint:['所有已登录用户使用此账号的播放音源。个人网易云登录仅用于导入歌单。','Signed-in listeners use this source. Personal NetEase accounts are only used to import playlists.','ログインしたユーザーはこの音源を利用します。個人のNetEaseアカウントはプレイリストの取込専用です。'],
  bind:['扫码绑定账号','Bind with QR code','QRコードで連携'], rebind:['更换账号','Replace account','アカウント変更'], check:['检查状态','Check status','状態を確認'], disable:['停用','Disable','無効にする'], enable:['启用','Enable','有効にする'], remove:['移除音源账号','Remove source account','音源アカウントを解除'], cancel:['取消','Cancel','キャンセル'], confirm:['确认操作','Confirm action','操作を確認'],
  removeHint:['移除后，所有用户的在线播放将暂停，直到重新绑定音源。','Removing the source pauses online playback for all users until another account is bound.','解除すると再連携するまで全ユーザーのオンライン再生が停止します。'],
  waiting:['请在网易云音乐中扫描二维码','Scan with NetEase Cloud Music','NetEase Cloud Musicでスキャンしてください'], scanned:['已扫描，请在手机上确认','Scanned. Confirm on your phone.','スキャン済み。スマートフォンで確認してください。'], expired:['二维码已过期，请重新生成','QR code expired. Generate a new one.','QRコードの期限切れです。再生成してください。'], qrAlt:['网易云账号绑定二维码','NetEase account QR code','NetEase連携用QRコード'],
  ready:['可用','Ready','利用可能'], unconfigured:['尚未绑定','Not configured','未設定'], disabled:['已停用','Disabled','無効'], lastChecked:['最近检查','Last checked','最終確認'], noAccount:['尚无绑定账号','No account bound','連携アカウントなし'],
  createInvite:['生成邀请码','Create invitation','招待コードを作成'], inviteHint:['单次使用，7 天内有效。请自行发给受邀用户。','Single use, valid for 7 days. Share it with the invited person.','1回限り、7日間有効です。招待する相手に共有してください。'], copy:['复制','Copy','コピー'], copied:['已复制','Copied','コピーしました'], tokenHint:['此凭据只显示一次，请复制保存。','This token is shown once. Copy it now.','このトークンは一度だけ表示されます。コピーしてください。'], revoke:['撤销','Revoke','取り消す'], used:['已使用','Used','使用済み'], revoked:['已撤销','Revoked','取消済み'], validUntil:['有效期至','Expires','有効期限'],
  user:['用户','User','ユーザー'], administrator:['管理员','Administrator','管理者'], active:['正常','Active','有効'], resetUser:['生成重置凭据','Create reset token','再設定トークンを作成'], resetHint:['重置凭据 1 小时有效，此用户的已有会话将立即退出。','The token expires in 1 hour. Existing sessions for this user will be signed out immediately.','トークンは1時間有効です。このユーザーの既存セッションは直ちに終了します。'], disableHint:['停用后会立即退出该用户的全部网站会话。','Disabling signs this user out of every site session.','無効にするとこのユーザーの全セッションが終了します。'],
  database:['数据库','Database','データベース'], failures:['近 24 小时音源失败次数','Source failures in the last 24 hours','過去24時間の音源エラー'], refresh:['刷新','Refresh','更新'], empty:['暂无记录','No records','記録はありません'], adminOnly:['仅管理员可以访问此页面','Only administrators can access this page','管理者のみアクセスできます'],
  notConfigured:['网站账号服务尚未配置。你仍可使用本地播放器。','Site accounts are not configured. Local playback is still available.','サイトアカウントは未設定です。ローカル再生は利用できます。'], setupHint:['使用部署时设置的初始化口令创建首个管理员。','Use the deployment setup token to create the first administrator.','デプロイ時のトークンで最初の管理者を作成します。'],
  synced:['已同步','Synced','同期済み'], syncing:['同步中…','Syncing…','同期中…'], retry:['等待同步，点击重试','Waiting to sync. Retry','同期待ち・再試行'], cloudHint:['歌单和收听记录随账号同步，本地音频不上传。','Playlists and listening history sync with your account. Local audio stays on this device.','プレイリストと再生履歴は同期されます。ローカル音声はアップロードされません。'],
  importTitle:['导入此设备已有内容？','Import existing device data?','この端末の既存データを取り込みますか？'], importHint:['将访客歌单和收听记录合并到此账号。原始数据会保留，本地音频不会上传。','Merge guest playlists and listening history into this account. Originals stay on this device; audio is not uploaded.','ゲストのプレイリストと再生履歴を統合します。元のデータは保持され、音声はアップロードされません。'], import:['导入到此账号','Import into this account','このアカウントに取り込む'], later:['暂不导入','Not now','後で'],
  missing:['此设备无文件','File missing on this device','この端末にファイルがありません'], attach:['选择本地文件','Choose local file','ローカルファイルを選択'], guest:['访客模式','Guest mode','ゲストモード'], authHint:['登录 Lumen 后使用公共音源，并同步歌单和收听记录。','Sign in to Lumen to use the shared music source and sync your library.','Lumenにログインして共有音源とライブラリ同期を利用できます。'], personal:['个人网易云账号 · 仅导入歌单','Personal NetEase account · playlist import only','個人のNetEaseアカウント · 取込専用'],
  AUTH_REQUIRED:['请先登录 Lumen','Sign in to Lumen first','先にLumenへログインしてください'], SOURCE_UNCONFIGURED:['管理员尚未配置音源账号','The administrator has not configured a music source','管理者が音源を設定していません'], SOURCE_DISABLED:['公共音源已停用','The shared source is disabled','共有音源は無効です'], SOURCE_EXPIRED:['公共音源登录已失效，请联系管理员','The shared source session expired. Contact the administrator.','共有音源のログイン期限切れです。管理者に連絡してください。'], SOURCE_UNAVAILABLE:['音源服务暂时不可用，请稍后重试','Music service is temporarily unavailable. Try again later.','音源サービスが一時的に利用できません。後で再試行してください。'], SOURCE_KEY_MISSING:['音源加密配置不可用，请检查部署设置','Source encryption is unavailable. Check deployment settings.','音源の暗号化設定を確認してください。'],
  RATE_LIMITED:['请求过于频繁，请稍后重试','Too many requests. Try again shortly.','リクエストが多すぎます。しばらくして再試行してください。'], DATABASE_UNAVAILABLE:['账号与同步服务暂时不可用','Account and sync services are unavailable','アカウント・同期サービスを利用できません'], LOGIN_INVALID:['用户名或密码错误，或账号已停用','Invalid credentials or disabled account','認証情報が正しくないかアカウントが無効です'], PASSWORD_INVALID:['密码长度应为 12–128 个字符','Use a password with 12–128 characters','パスワードは12〜128文字にしてください'], USERNAME_INVALID:['用户名应为 3–32 位小写字母、数字或下划线','Use 3–32 lowercase letters, digits or underscores','ユーザー名は半角小文字・数字・下線で3〜32文字にしてください'], USERNAME_TAKEN:['此用户名已被使用','Username is already taken','このユーザー名は使用されています'], INVITE_INVALID:['邀请码无效、已使用或已过期','Invitation is invalid, used or expired','招待コードが無効・使用済み・期限切れです'], RESET_INVALID:['重置凭据无效或已过期','Reset token is invalid or expired','再設定トークンが無効または期限切れです'], SETUP_DENIED:['初始化口令不正确或未配置','Setup token is incorrect or not configured','初期設定トークンが正しくないか未設定です'], SETUP_CLOSED:['管理员初始化已完成，请登录','Setup is complete. Sign in instead.','初期設定済みです。ログインしてください'], LAST_ADMIN:['不能停用最后一个管理员','The last administrator cannot be disabled','最後の管理者を無効にできません'], CSRF_REJECTED:['会话已变化，请刷新后重试','Session changed. Refresh and try again.','セッションが変更されました。更新してください'], QR_STALE:['二维码已被取消或替换，请重新生成','QR flow was cancelled or replaced. Start again.','QRコードが取消・更新されました。再生成してください'], REQUEST_FAILED:['操作失败，请重试','Request failed. Try again.','操作に失敗しました。再試行してください'], STORAGE_UNAVAILABLE:['本地存储不可用，请检查空间','Local storage is unavailable. Check free space.','ローカル保存を利用できません。空き容量を確認してください'],
} as const;
export type SiteWord = keyof typeof words;
export function siteText(lang: Lang, key: string) {
  const text = words[key as SiteWord] || words.REQUEST_FAILED;
  return text[lang === 'zh' ? 0 : lang === 'ja' ? 2 : 1];
}
export function useSiteText() { const { lang } = useI18n(); return (key: string) => siteText(lang, key); }
